# vim: ft=ansible
---

driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_verbose: true


platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: ubuntu-15.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:
